def dhcp_config(SITE_CODE,SITE_NAME,DHCP_SCOPE_NAME,VLAN_ID):
        DHCP_SERVER_ADDRESS = "10."+SITE_CODE+"0.1"
        DHCP_SCOPE_ADDRESS = "10."+SITE_CODE+"."+str(VLAN_ID)
        DHCP_SCOPE_NETWORK = DHCP_SCOPE_ADDRESS+".0"
        print("netsh Dhcp Server "+DHCP_SERVER_ADDRESS+" add scope "+DHCP_SCOPE_NETWORK+" 255.255.255.0 "+DHCP_SCOPE_NAME+" "+DHCP_SCOPE_NAME)
        print("netsh Dhcp Server "+DHCP_SERVER_ADDRESS+" Scope "+DHCP_SCOPE_NETWORK+" set state 1")
        print("netsh Dhcp Server "+DHCP_SERVER_ADDRESS+" Scope "+DHCP_SCOPE_NETWORK+" add iprange "+DHCP_SCOPE_ADDRESS+".1 "+DHCP_SCOPE_ADDRESS+".254")
        print("netsh Dhcp Server "+DHCP_SERVER_ADDRESS+" Scope "+DHCP_SCOPE_NETWORK+" add excluderange "+DHCP_SCOPE_ADDRESS+".1 "+DHCP_SCOPE_ADDRESS+".3")
        print("netsh Dhcp Server "+DHCP_SERVER_ADDRESS+" Scope "+DHCP_SCOPE_NETWORK+" set optionvalue 51 DWORD \"604800\"")
        print("netsh Dhcp Server "+DHCP_SERVER_ADDRESS+" Scope "+DHCP_SCOPE_NETWORK+" set optionvalue 3 IPADDRESS "+DHCP_SCOPE_ADDRESS+".3")
        print("netsh Dhcp Server "+DHCP_SERVER_ADDRESS+" Scope "+DHCP_SCOPE_NETWORK+" set optionvalue 15 STRING \"domain.com\"")
        print("netsh Dhcp Server "+DHCP_SERVER_ADDRESS+" Scope "+DHCP_SCOPE_NETWORK+" set optionvalue 44 IPADDRESS \"10.0.0.2\" \"10.0.128.2\"")
        print("netsh Dhcp Server "+DHCP_SERVER_ADDRESS+" Scope "+DHCP_SCOPE_NETWORK+" set optionvalue 46 BYTE \"4\"")
        print("netsh Dhcp Server "+DHCP_SERVER_ADDRESS+" Scope "+DHCP_SCOPE_NETWORK+" set optionvalue 6 IPADDRESS 10.0.0.2 10.0.128.2")
        print()
def vtp_config(DHCP_SCOPE_NAME,VLAN_ID):
        print()
        print("vlan "+str(VLAN_ID))
        print("name "+DHCP_SCOPE_NAME)
        print("exit")
        print()
def hsrp_active_config(SITE_CODE,DHCP_SCOPE_NAME,VLAN_ID):
        DHCP_SCOPE_ADDRESS = "10."+SITE_CODE+"."+str(VLAN_ID)
        DHCP_SERVER_ADDRESS = "10."+SITE_CODE+"0.1"
        print("interface Vlan"+str(VLAN_ID))
        print("description "+DHCP_SCOPE_NAME)
        print("ip address "+DHCP_SCOPE_ADDRESS+".1 255.255.255.0")
        print("ip helper-address "+DHCP_SERVER_ADDRESS)
        print("standby "+str(VLAN_ID)+" ip "+DHCP_SCOPE_ADDRESS+".3")
        print("standby "+str(VLAN_ID)+" priority 105")
        print("standby "+str(VLAN_ID)+" preempt delay minimum 60 reload")
        print()
def hsrp_standby_config(SITE_CODE,DHCP_SCOPE_NAME,VLAN_ID):
        DHCP_SCOPE_ADDRESS = "10."+SITE_CODE+"."+str(VLAN_ID)
        DHCP_SERVER_ADDRESS = "10."+SITE_CODE+"0.1"
        print("interface Vlan"+str(VLAN_ID))
        print("description "+DHCP_SCOPE_NAME)
        print("ip address "+DHCP_SCOPE_ADDRESS+".2 255.255.255.0")
        print("ip helper-address "+DHCP_SERVER_ADDRESS)
        print("standby "+str(VLAN_ID)+" ip "+DHCP_SCOPE_ADDRESS+".3")
        print()
def access_port_config(DHCP_SCOPE_NAME,VLAN_ID):
        print("description "+DHCP_SCOPE_NAME)        
        print("switchport access vlan "+str(VLAN_ID))
        print()
def vlan_config(SITE_CODE,SITE_NAME):
        
        USER_VLAN_ID_RANGE = range(4,8)
        DHCP_SERVER_ADDRESS = "10."+SITE_CODE+"0.1"

        print("********************************************************************")
        print("DHCP SERVER CONFIG for " + SITE_NAME +" "+DHCP_SERVER_ADDRESS)
        print("********************************************************************")
        print()      
        dhcp_config(SITE_CODE,SITE_NAME,str(SITE_NAME)+"-USER-1",4)
        dhcp_config(SITE_CODE,SITE_NAME,str(SITE_NAME)+"-USER-2",5)
        dhcp_config(SITE_CODE,SITE_NAME,str(SITE_NAME)+"-USER-3",6)
        dhcp_config(SITE_CODE,SITE_NAME,str(SITE_NAME)+"-USER-4",7)
        dhcp_config(SITE_CODE,SITE_NAME,str(SITE_NAME)+"-SERVER",16)
        dhcp_config(SITE_CODE,SITE_NAME,str(SITE_NAME)+"-VDI",24)
        dhcp_config(SITE_CODE,SITE_NAME,str(SITE_NAME)+"-PRINTER",33)
        dhcp_config(SITE_CODE,SITE_NAME,str(SITE_NAME)+"-VC",36)
        dhcp_config(SITE_CODE,SITE_NAME,str(SITE_NAME)+"-WLAN",48)
        dhcp_config(SITE_CODE,SITE_NAME,str(SITE_NAME)+"-GUEST-WLAN",63)
        print()
        print("********************************************************************")
        print("VTP SERVER CONFIG for " + SITE_NAME)
        print("********************************************************************")
        print()
        vtp_config(str(SITE_NAME)+"-USER-1",4)
        vtp_config(str(SITE_NAME)+"-USER-2",5)
        vtp_config(str(SITE_NAME)+"-USER-3",6)
        vtp_config(str(SITE_NAME)+"-USER-4",7)
        vtp_config(str(SITE_NAME)+"-SERVER",16)
        vtp_config(str(SITE_NAME)+"-VDI",24)
        vtp_config(str(SITE_NAME)+"-PRINTER",33)
        vtp_config(str(SITE_NAME)+"-VC",36)
        vtp_config(str(SITE_NAME)+"-WLAN",48)
        vtp_config(str(SITE_NAME)+"-GUEST-WLAN",63)
        print()        
        print("********************************************************************")
        print("HSRP ACTIVE CONFIG for " + SITE_NAME)
        print("********************************************************************")
        print()
        hsrp_active_config(SITE_CODE,str(SITE_NAME)+"-USER-1",4)
        hsrp_active_config(SITE_CODE,str(SITE_NAME)+"-USER-2",5)
        hsrp_active_config(SITE_CODE,str(SITE_NAME)+"-USER-3",6)
        hsrp_active_config(SITE_CODE,str(SITE_NAME)+"-USER-4",7)
        hsrp_active_config(SITE_CODE,str(SITE_NAME)+"-SERVER",16)
        hsrp_active_config(SITE_CODE,str(SITE_NAME)+"-VDI",24)
        hsrp_active_config(SITE_CODE,str(SITE_NAME)+"-PRINTER",33)
        hsrp_active_config(SITE_CODE,str(SITE_NAME)+"-VC",36)
        hsrp_active_config(SITE_CODE,str(SITE_NAME)+"-WLAN",48)
        hsrp_active_config(SITE_CODE,str(SITE_NAME)+"-GUEST-WLAN",63)
        print()        
        print("********************************************************************")
        print("HSRP STANDBY CONFIG for " + SITE_NAME)
        print("********************************************************************")
        print()
        hsrp_standby_config(SITE_CODE,str(SITE_NAME)+"-USER-1",4)
        hsrp_standby_config(SITE_CODE,str(SITE_NAME)+"-USER-2",5)
        hsrp_standby_config(SITE_CODE,str(SITE_NAME)+"-USER-3",6)
        hsrp_standby_config(SITE_CODE,str(SITE_NAME)+"-USER-4",7)
        hsrp_standby_config(SITE_CODE,str(SITE_NAME)+"-SERVER",16)
        hsrp_standby_config(SITE_CODE,str(SITE_NAME)+"-VDI",24)
        hsrp_standby_config(SITE_CODE,str(SITE_NAME)+"-PRINTER",33)
        hsrp_standby_config(SITE_CODE,str(SITE_NAME)+"-VC",36)
        hsrp_standby_config(SITE_CODE,str(SITE_NAME)+"-WLAN",48)
        hsrp_standby_config(SITE_CODE,str(SITE_NAME)+"-GUEST-WLAN",63)
        print()         
        print("********************************************************************")
        print("ACCESS SWITCH PORT CONFIG for " + SITE_NAME)
        print("********************************************************************")
        print()
        access_port_config(str(SITE_NAME)+"-USER-1",4)
        access_port_config(str(SITE_NAME)+"-USER-2",5)
        access_port_config(str(SITE_NAME)+"-USER-3",6)
        access_port_config(str(SITE_NAME)+"-USER-4",7)
        access_port_config(str(SITE_NAME)+"-SERVER",16)
        access_port_config(str(SITE_NAME)+"-VDI",24)
        access_port_config(str(SITE_NAME)+"-PRINTER",33)
        access_port_config(str(SITE_NAME)+"-VC",36)
        access_port_config(str(SITE_NAME)+"-WLAN",48)
        access_port_config(str(SITE_NAME)+"-GUEST-WLAN",63)
vlan_config("SITE_CODE","SITE_NAME")

